<a href="https://colab.research.google.com/github/Ailsasahda13/DataMining-Semester4/blob/main/Jobsheet%2013%20-%20ANN/Latihan%20Heart%20Disease.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler

from sklearn.neural_network import MLPClassifier

from sklearn.metrics import accuracy_score
from sklearn.metrics import classification_report

In [2]:
df = pd.read_csv('Heart_Disease_Prediction.csv')

df.head()

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [3]:
df.info()

df.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 270 entries, 0 to 269
Data columns (total 14 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      270 non-null    int64
 1   Sex                      270 non-null    int64
 2   Chest pain type          270 non-null    int64
 3   BP                       270 non-null    int64
 4   Cholesterol              270 non-null    int64
 5   FBS over 120             270 non-null    int64
 6   EKG results              270 non-null    int64
 7   Max HR                   270 non-null    int64
 8   Exercise angina          270 non-null    int64
 9   ST depression            270 non-null    float64
 10  Slope of ST              270 non-null    int64
 11  Number of vessels fluro  270 non-null    int64
 12  Thallium                 270 non-null    int64
 13  Heart Disease            270 non-null    object
dtypes: float64(1), int64(12), object(1)
memory usage: 29.7+ KB

,Age,Sex,Chest pain type,BP,Cholesterol,FBS over 120,EKG results,Max HR,Exercise angina,ST depression,Slope of ST,Number of vessels fluro,Thallium,Heart Disease
0,70,1,4,130,322,0,2,109,0,2.4,2,3,3,Presence
1,67,0,3,115,564,0,2,160,0,1.6,2,0,7,Absence
2,57,1,2,124,261,0,0,141,0,0.3,1,0,7,Presence
3,64,1,4,128,263,0,0,105,1,0.2,2,1,7,Absence
4,74,0,2,120,269,0,2,121,1,0.2,1,1,3,Absence

In [4]:
le = LabelEncoder()

df['Heart Disease'] = le.fit_transform(df['Heart Disease'])

In [5]:
X = df.drop('Heart Disease', axis=1)

y = df['Heart Disease']

In [6]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [7]:
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)

X_test = scaler.transform(X_test)

In [8]:
hidden_layers = [
    (10,10,6),
    (6,8,9),
    (6,9,1),
    (6,3,9),
    (7,10,8)
]

In [9]:
for hl in hidden_layers:

    model = MLPClassifier(
        hidden_layer_sizes=hl,
        activation='relu',
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)

    prediksi = model.predict(X_test)

    acc = accuracy_score(y_test, prediksi)

    print(f"Hidden Layer = {hl}")
    print(f"Accuracy = {acc*100:.2f}%")
    print("-"*30)

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Hidden Layer = (10, 10, 6)
Accuracy = 83.33%
------------------------------
Hidden Layer = (6, 8, 9)
Accuracy = 87.04%
------------------------------
Hidden Layer = (6, 9, 1)
Accuracy = 61.11%
------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Hidden Layer = (6, 3, 9)
Accuracy = 88.89%
------------------------------
Hidden Layer = (7, 10, 8)
Accuracy = 83.33%
------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

In [10]:
activations = [
    'identity',
    'logistic',
    'tanh',
    'relu'
]

In [11]:
for act in activations:

    model = MLPClassifier(
        hidden_layer_sizes=(6,3,9),
        activation=act,
        max_iter=1000,
        random_state=42
    )

    model.fit(X_train, y_train)

    prediksi = model.predict(X_test)

    acc = accuracy_score(y_test, prediksi)

    print(f"Activation = {act}")
    print(f"Accuracy = {acc*100:.2f}%")
    print("-"*30)

Activation = identity
Accuracy = 92.59%
------------------------------
Activation = logistic
Accuracy = 61.11%
------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

Activation = tanh
Accuracy = 83.33%
------------------------------
Activation = relu
Accuracy = 88.89%
------------------------------

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(

In [12]:
model = MLPClassifier(
    hidden_layer_sizes=(6,3,9),
    activation='relu',
    max_iter=1000,
    random_state=42
)

model.fit(X_train, y_train)

prediksi = model.predict(X_test)

print("Accuracy :", accuracy_score(y_test,prediksi))

print(classification_report(y_test,prediksi))

Accuracy : 0.8888888888888888
              precision    recall  f1-score   support

           0       0.91      0.91      0.91        33
           1       0.86      0.86      0.86        21

    accuracy                           0.89        54
   macro avg       0.88      0.88      0.88        54
weighted avg       0.89      0.89      0.89        54

/usr/local/lib/python3.12/dist-packages/sklearn/neural_network/_multilayer_perceptron.py:691: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (1000) reached and the optimization hasn't converged yet.
  warnings.warn(